# Generated by Django 5.2.7 on 2025-11-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_otpverification_userprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=50, unique=True, verbose_name='رقم الهاتف'),
        ),
    ]
