# Generated by Django 5.2.7 on 2025-11-06 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_userprofile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True, verbose_name='رمز الجهاز (FCM Token)')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=10, verbose_name='نوع الجهاز')),
                ('device_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='معرف الجهاز')),
                ('device_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الجهاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='آخر استخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز جهاز',
                'verbose_name_plural': 'رموز الأجهزة',
                'ordering': ['-last_used'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='chat_device_user_id_715e97_idx'), models.Index(fields=['token'], name='chat_device_token_2cc128_idx')],
            },
        ),
    ]
