# Generated by Django 5.2.7 on 2025-11-06 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_devicetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_time', models.DateTimeField(auto_now=True, verbose_name='آخر رسالة')),
                ('message_count', models.IntegerField(default=0, verbose_name='عدد الرسائل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('contact_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_contacts_of', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المتواصل معه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_contacts', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مستخدم متواصل معه',
                'verbose_name_plural': 'المستخدمون المتواصل معهم',
                'ordering': ['-last_message_time'],
                'indexes': [models.Index(fields=['user', '-last_message_time'], name='chat_recent_user_id_1a21e7_idx')],
                'unique_together': {('user', 'contact_user')},
            },
        ),
    ]
