# Generated by Django 5.2.7 on 2025-11-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_story_text_content_and_metadata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sessiondevice',
            new_name='chat_sessio_user_id_641886_idx',
            old_name='chat_sessio_user_id_b29bd7_idx',
        ),
        migrations.RenameIndex(
            model_name='sessiondevice',
            new_name='chat_sessio_session_d3fdbd_idx',
            old_name='chat_sessio_session_cb885f_idx',
        ),
        migrations.RenameIndex(
            model_name='sessiondevice',
            new_name='chat_sessio_device__0be179_idx',
            old_name='chat_sessio_device__43f410_idx',
        ),
        migrations.RenameIndex(
            model_name='story',
            new_name='chat_story_user_id_249f09_idx',
            old_name='chat_story_user_id_c25efb_idx',
        ),
        migrations.RenameIndex(
            model_name='story',
            new_name='chat_story_expires_f10d54_idx',
            old_name='chat_story_expires_4f361b_idx',
        ),
    ]
