# Generated by Django 5.2.7 on 2025-11-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_rename_chat_sessio_user_id_b29bd7_idx_chat_sessio_user_id_641886_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='messages/original/', verbose_name='الملف الأصلي'),
        ),
    ]
