# Generated by Django 5.2.7 on 2025-11-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_callsession_callparticipant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='callparticipant',
            new_name='chat_callpa_session_dc20e8_idx',
            old_name='chat_call_session_user_idx',
        ),
        migrations.RenameIndex(
            model_name='callparticipant',
            new_name='chat_callpa_user_id_7aa6ad_idx',
            old_name='chat_call_user_connected_idx',
        ),
        migrations.RenameIndex(
            model_name='callsession',
            new_name='chat_callse_status_6c85cc_idx',
            old_name='chat_calls_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='callsession',
            new_name='chat_callse_room_id_d0fe3c_idx',
            old_name='chat_calls_room_status_idx',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الهاتف'),
        ),
    ]
