# Generated by Django 5.2.7 on 2025-11-11 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_chatroom_room_type_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentcontact',
            options={'ordering': ['-is_pinned', '-pinned_at', '-last_message_time'], 'verbose_name': 'مستخدم متواصل معه', 'verbose_name_plural': 'المستخدمون المتواصل معهم'},
        ),
        migrations.RemoveIndex(
            model_name='recentcontact',
            name='chat_recent_user_id_1a21e7_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='مثبتة'),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التثبيت'),
        ),
        migrations.AddField(
            model_name='message',
            name='pinned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_pinned', to=settings.AUTH_USER_MODEL, verbose_name='تم التثبيت بواسطة'),
        ),
        migrations.AddField(
            model_name='recentcontact',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='محادثة مثبّتة'),
        ),
        migrations.AddField(
            model_name='recentcontact',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ تثبيت المحادثة'),
        ),
        migrations.AddIndex(
            model_name='recentcontact',
            index=models.Index(fields=['user', '-is_pinned', '-pinned_at', '-last_message_time'], name='chat_recent_user_id_63e3d7_idx'),
        ),
    ]
